NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy stands for Numerical Python.

**Why do we use numpy arrays instead of traditional lists ?**



NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

:💡The source code for NumPy is located at this github repository https://github.com/numpy/numpy
(after class activity)

 Type this in your command line or terminal  to install NumPy if not done earlier : pip install numpy

1)Once NumPy is installed, import it in your applications by adding the import keyword:

In [ ]:
import numpy

You could also import NumPy using this command 
By doing this you could use np instead of NumPy for further usage 

In [ ]:
import numpy as np

Creating our first NumPy array 


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
print(arr)

[1 2 3 4 5]


To check your NumPy version type in 
import numpy as np

print(np.__version__)

## Dimensions In Arrays 

0-D Arrays


In [ ]:
a = np.array(42)

print(a)

42


1-D Arrays - An array that has 0-D arrays as its elements 

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


2-D Arrays - An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


3-D arrays - An array that has 2-D arrays (matrices) as its elements is called 3-D array.



In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Command to check the dimension of a NumPy array 

In [ ]:
print(a.ndim)

3


## NumPy Array Indexing

In [ ]:
a = np.array([1, 2, 3, 4])

print(a[0]) # accessing the first element of the 1-D array 

1


Accessing 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1,10,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  10


Access 3-D Arrays

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Slicing arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


Negetive Slicing 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5:])

[3 4 5 6 7]


STEP Function in NumPy arrays 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


Step Function in 2-D arrays 

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:])

[ 7  8  9 10]


Converting data types in NumPy 

In [ ]:
import numpy as np

arr = np.array([1.23, 2.15,17.6])# the floating point is converted to integer by truncation without rounding off 

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[ 1  2 17]
int64


NumPy array shape 

IMPORTANCE- shape of the array should be known for matrix multiplications 

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(a.shape)

(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


NumPy Reshape

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Converting 1D to 2D arrays 

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new = a.reshape(4, 3)

print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Converting 1D to 3D arrays 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Conditions to be taken care of while reshaping a NumPy array 

In the previous example we have reshaped the 1D array to a 3D array with 2,3,2 elements which is equal to 2*3 *2 = 12 which is equal the length of 1D array 

split function in numpy 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Search function in NumPy

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)# gives back the index of the array where arr===4

(array([3, 5, 6]),)


<h1> Assignment 1 </h1>
<h2> Completion of this assignment is required for certification </h2>

Convert the given  1D array to a 2D array with 2 rows and 4 elements in each row 
take the second element from the first row of  this new array and multiply it with the the third element of the 1D array and convert this to a float data type 

In [ ]:
import numpy as np  
a=np.array([1,2,3,4,5,6,7,8])
arr=a.reshape(2,4)
b=arr[0][1]
c=a[2]
print(arr)
print(float(b*c))














[[1 2 3 4]
 [5 6 7 8]]
6.0


### Introduction to Pandas 




Pandas is an open-source library that is made mainly for working with relational or labeled data both easily and intuitively. 

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

pip install pandas - use this command in the command line to install pandas 

In [ ]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas

Now we will create a dataframe from scratch 

In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "TATA"],
  'rating': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  rating
0    BMW       3
1  Volvo       7
2   TATA       2


In [ ]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "TATA"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   TATA         2


Series in Pandas 

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


In [ ]:
import pandas as pd

df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/loan_train.csv')

#print(df) 
print(df.head())

   Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \
0           0             0     PAIDOFF       1000     30       9/8/2016   
1           2             2     PAIDOFF       1000     30       9/8/2016   
2           3             3     PAIDOFF       1000     15       9/8/2016   
3           4             4     PAIDOFF       1000     30       9/9/2016   
4           6             6     PAIDOFF       1000     30       9/9/2016   

    due_date  age             education  Gender  
0  10/7/2016   45  High School or Below    male  
1  10/7/2016   33              Bechalor  female  
2  9/22/2016   27               college    male  
3  10/8/2016   28               college  female  
4  10/8/2016   29               college    male  


Data Cleaning 

In [ ]:
import pandas as pd

filename ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"



In [ ]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [ ]:
df = pd.read_csv(filename, names = headers)
display(df)

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19    3.40              10.0        102   
4            136         mpfi  3.19    3.40               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01    3.40              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]


<div>So, how do we identify all those missing values and deal with them?</div> 

<b>How to work with missing data?</b>

Steps for working with missing data:

<ol>
    <li>Identify missing data</li>
    <li>Deal with missing data</li>
    <li>Correct data format</li>
</ol>


Identifying the missing values 

In [ ]:
import numpy as np

# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3               NaN  alfa-romero       gas        std          two   
1          3               NaN  alfa-romero       gas        std          two   
2          1               NaN  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

<h3 id="deal_missing_values">Deal with missing data</h3>
<b>How to deal with missing data?</b>

<ol>
    <li>Drop data<br>
        a. Drop the whole row<br>
        b. Drop the whole column
    </li>
    <li>Replace data<br>
        a. Replace it by mean<br>
        b. Replace it by frequency<br>
        c. Replace it based on other functions
    </li>
</ol>

In [ ]:
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis=0)
print("Average of normalized-losses:", avg_norm_loss)

Average of normalized-losses: 122.0


In [ ]:
df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=True)

In [ ]:
avg_bore=df['bore'].astype('float').mean(axis=0)
print("Average of bore:", avg_bore)

Average of bore: 3.3307106598984775


In [ ]:
df["bore"].replace(np.nan, avg_bore, inplace=True)

<h2 id="data_normalization">Data Normalization</h2>

<b>Why normalization?</b>

<p>Normalization is the process of transforming values of several variables into a similar range. Typical normalizations include scaling the variable so the variable average is 0, scaling the variable so the variance is 1, or scaling the variable so the variable values range from 0 to 1.
</p>

<b>Example</b>

<p>To demonstrate normalization, let's say we want to scale the columns "length", "width" and "height".</p>
<p><b>Target:</b> would like to normalize those variables so their value ranges from 0 to 1</p>
<p><b>Approach:</b> replace original value by (original value)/(maximum value)</p>


In [ ]:
# replace (original value) by (original value)/(maximum value)
df['length'] = df['length']/df['length'].max()
df['width'] = df['width']/df['width'].max()

In [ ]:
display(df['length'])

0      0.811148
1      0.811148
2      0.822681
3      0.848630
4      0.848630
         ...   
196    0.907256
197    0.907256
198    0.907256
199    0.907256
200    0.907256
Name: length, Length: 201, dtype: float64

<h1>Assignment 2 </h2>


<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h1> Question  #1: </h1>

<b>Based on the example above, replace NaN in "stroke" column with the mean value.</b>

</div>



In [ ]:
import pandas as pd

filename ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

df = pd.read_csv(filename, names = headers)
df.replace("?", np.nan, inplace = True)                                                 
df.head(5)                                                         #display first 5 rows
avg_stroke = df["stroke"].astype("float").mean(axis=0)             #axis=1->takes value horizontally axis=0->vertically
print(avg_stroke)
df["stroke"].replace(np.nan, avg_stroke, inplace=True)
display(df)

3.2554228855721337


symboling normalized-losses         make fuel-type aspiration  \
0            3               NaN  alfa-romero       gas        std   
1            3               NaN  alfa-romero       gas        std   
2            1               NaN  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19    3.40              10.0        102   
4            136         mpfi  3.19    3.40               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01    3.40              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h1> Question #2: </h1>

<b>According to the example above, normalize the column "height".</b>

</div>

In [ ]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

df = pd.read_csv(filename, names = headers)
df['height'] = df['height']/df['height'].max()
display(df['height'])

0      0.816054
1      0.816054
2      0.876254
3      0.908027
4      0.908027
         ...   
200    0.928094
201    0.928094
202    0.928094
203    0.928094
204    0.928094
Name: height, Length: 205, dtype: float64

 <div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h1> Question  #3: </h1>

<b>Merge the new dataframe to the original dataframe, then drop the column 'aspiration'.</b>

</div>
<b> Note: This functionn is not taught in class but is given to encourage reseach for solving this paricular problem </b>
<h3> Googling is an important skill to be successful in becoming an efficient programmer </h3>
<h4> Happy Googling </h4>


In [ ]:
from pandas import *
from numpy import *


filename ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

df = read_csv(filename, names = headers)
af=df['height'] = df['height']/df['height'].max()
nf=df.append(af)
nf.drop(['aspiration'],axis=1)


























symboling normalized-losses         make fuel-type num-of-doors  \
0             3.0                 ?  alfa-romero       gas          two   
1             3.0                 ?  alfa-romero       gas          two   
2             1.0                 ?  alfa-romero       gas          two   
3             2.0               164         audi       gas         four   
4             2.0               164         audi       gas         four   
...           ...               ...          ...       ...          ...   
201          -1.0                95        volvo       gas         four   
202          -1.0                95        volvo       gas         four   
203          -1.0                95        volvo    diesel         four   
204          -1.0                95        volvo       gas         four   
height        NaN               NaN          NaN       NaN          NaN   

         body-style drive-wheels engine-location  wheel-base  length  ...  \
0       convertible          rwd           front        88.6   168.8  ...   
1       convertible          rwd           front        88.6   168.8  ...   
2         hatchback          rwd           front        94.5   171.2  ...   
3             sedan          fwd           front        99.8   176.6  ...   
4             sedan          4wd           front        99.4   176.6  ...   
...             ...          ...             ...         ...     ...  ...   
201           sedan          rwd           front       109.1   188.8  ...   
202           sedan          rwd           front       109.1   188.8  ...   
203           sedan          rwd           front       109.1   188.8  ...   
204           sedan          rwd           front       109.1   188.8  ...   
height          NaN          NaN             NaN         NaN     NaN  ...   

             195       196       197       198       199       200       201  \
0            NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1            NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2            NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3            NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4            NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...          ...       ...       ...       ...       ...       ...       ...   
201          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
202          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
203          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
204          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
height  0.961538  0.939799  0.961538  0.939799  0.961538  0.928094  0.928094   

             202       203       204  
0            NaN       NaN       NaN  
1            NaN       NaN       NaN  
2            NaN       NaN       NaN  
3            NaN       NaN       NaN  
4            NaN       NaN       NaN  
...          ...       ...       ...  
201          NaN       NaN       NaN  
202          NaN       NaN       NaN  
203          NaN       NaN       NaN  
204          NaN       NaN       NaN  
height  0.928094  0.928094  0.928094  

[206 rows x 230 columns]